# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers 2016"
email: "womentechmakersit@gmail.com"
description: "Women Techmakers: Create, Connect, Celebrate includerà discussioni con donne leader nei settori IT, opportunità di fare networking, sessioni dimostrative."
baseurl: "/wtm2016"
url: "http://gdgbari.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Bari"
organizerAlternateName: "Google Developer Group Bari"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdgbari@gmail.com"
organizerLogo: "/../img/seo/organizer-logo.png"
organizerLink: "http://gdgbari.github.io"

# Head
metaKeywords: "event, gdg, women, techmakers, google, programming, android, chrome, developers, design, bari"
twitterAccount: "@WTMItalia"
socialImageSrcGooglePlus: "/img/seo/organizer-logo.png"
socialImageSrcTwitter: "/img/seo/organizer-logo.png"
socialImageSrcFacebook: "/img/seo/organizer-logo.png"
#socialImageSrcGooglePlus: "/img/organizers/wtm-mt.svg"
#socialImageSrcTwitter: "/img/organizers/wtm-mt.svg"
#socialImageSrcFacebook: "/../img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Programma"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "About"}
bottomNavigationLinks:
rightNavigationButtons:

# Hero Block
heroImage: "hero.png"
heroTitle: "Boost your idea <typeout>"
eventDate: "<br />dall’idea al business in 5 passi!"
typeoutTextValues: '"", "!"'
typeoutFallback: "!"
heroButtons:
 - {link: "https://www.eventbrite.it/e/biglietti-boost-your-idea-dallidea-al-business-in-5-passi-22875105055", text: "Registrati!"}

# About Block
aboutTitle: "About Women Techmakers"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "L'unico evento Women Techmakers (WTM) in Italia. Venite a Bari a scoprire cos'è WTM! Celebreremo le donne nella tecnologia e i loro successi." }
 - {title: "Workshop", image: "workshop.jpg", text: "Il Google Developer Group (GDG) di Bari presenta: la tecnologia Google in azione! Venite a scoprire cos'è un GDG e cosa si fa in un GDG, un giorno potreste farne parte anche voi!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Scopri gli speaker"
rockstarSpeakersButtonText: "Vedi tutti gli speaker"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Aula Magna Dip. di Ingegneria Civile e Architettura (Dicar)"
eventLocationLink: "#"
eventStreetAddress: "Via Orabona, 4"
eventAddressLocality: "Bari"
eventAddressLocalityRegion: "Bari"
eventPostalCode: "70126"
eventAddressCountry: "Italy"
eventStartTime: "2016-03-31T09:30"
eventDoorTime: "09:30"
eventEndTime: "2016-03-31T18:30"
eventPlaceCoordinates: "41.1090195,16.8792464"
mapCenterCoordinates: "41.1090195,16.8792464"
mapMobileCenterCoordinates: "41.1090195,16.8792464"

# Venue Block
#venueBlockTitle: "La Sede"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Sala Consiliare \"Pasolini\""
#venueFeatures: ["150 posti", "Proiettore con maxi schermo", "Presso centro commerciale Il Circo"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "wtm16"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "#"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/communities/100202454944694552166", icon: "google-plus"}
 - {link: "https://twitter.com/WTMItalia", icon: "twitter"}
 - {link: "https://www.facebook.com/womentechmakersit", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.womentechmakers.com/", text: "Women Techmakers"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:womentechmakersit@gmail.com", text: "womentechmakersit@gmail.com"}
 -
  title: "Related resources"
  links:
   - {link: "https://www.womentechmakers.com/", text: "Women Techmakers"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About WTM"
aboutUs: "<p ALIGN=Left>Women Techmakers nasce con lo scopo di condividere i principi di inclusione volti a sostenere, promuovere e incoraggiare le donne e le minoranze nella tecnologia.<br>Women Techmakers mira a incrementare la consapevolezza dell’esistenza di donne creative e leader in campo tecnologico ispirando così altre donne a mettersi in gioco in questo settore.<br><br>Women Techmakers é un’iniziativa patrocinata da Google.</p><br><p ALIGN=Left>Google si impegna a coltivare un ambiente di lavoro totalmente inclusivo in tutto il mondo. Una componente chiave di questa visione è mettere le donne nella condizione di poter perseguire i loro sogni e, così, progettare gli strumenti che potranno cambiare il mondo. Se le organizzazioni creano gli ambienti giusti, programmi e politiche adeguate, le donne nella tecnologia possono dare un contributo fondamentale.<br>Ecco perché, nel mese di Marzo, in cui si festeggia la Giornata Internazionale della Donna, Google sta lanciando una serie di eventi globali chiamati Women Techmakers orientati  ad accrescere la visibilità, le comunità e le risorse per le donne che vogliano cimentarsi, o che operano già, nei settori dell’Information Technology.<br>Stiamo quindi organizzando un evento presso il Politecnico di Bari, l’evento includerà discussioni con donne leader nei settori IT, sessioni tecniche, workshop, opportunità di fare networking.</p>"
# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Come Arrivare"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
#hackathonTitle: "Hackathon"
#enableHackathon: true

# Hackathon About Block
#aboutHackathonTitle: "Meet our themes"
#hackathonRows:
# - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
#judgesImage: "judges.jpg"
#judgesTitle: "Judges"

# Hackathon Prizes Block
#prizesTitle: "Prizes"
#prizes:
# - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
# - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
# - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
#hackathonLocationBlockTitle: "Location"
#hackathonLocationName: "Communa"
#hackathonLocationLink: "http://communa.net.ua/"
#hackathonStreetAddress: "1 Halytska St"
#hackathonAddressLocality: "Lviv"
#hackathonAddressLocalityRegion: "Lvivska"
#hackathonPostalCode: "79000"
#hackathonAddressCountry: "Ukraine"
#hackathonTimeTitle: "Hack through"
#hackathonStartTime: "2014-10-24T10:00"
#hackathonDoorTime: "09:00"
#hackathonEndTime: "2014-10-25T00:00"
#viewOnMap: "View on Google Maps"
#hackathonPlaceCoordinates: "49.840999, 24.031144"
#hackathonMapCenterCoordinates: "49.840696, 24.028754"
#hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
